# wrangler-dev.toml
name = "traffic-light-app-dev"
compatibility_date = "2024-01-01"

# D1 Database binding for local development
[[d1_databases]]
binding = "DB"
database_name = "traffic-light-demo"
database_id = "02485f82-5c1e-44ee-8fd0-935f282deceb"

[build]
command = "npm run build"

[site]
bucket = ".next/static"